[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "br, gzip"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://embed.tawk.to https://static.cloudflareinsights.com https://www.googletagmanager.com;
      style-src 'self' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      img-src 'self' https://images.unsplash.com data:;
      connect-src 'self' https://formspree.io/f/mnndlwnb https://*.tawk.to wss://*.tawk.to https://analytics.cloudflare.com https://www.google-analytics.com;
      frame-src 'self' https://*.tawk.to;
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://formspree.io/f/mnndlwnb;
    """